# =====================================================
# ARCHIVO DE CONFIGURACION EXTERNO - ms-pagos
# Este archivo va en la misma carpeta que el JAR
# El administrador completa los datos de conexion
# =====================================================

spring.application.name=ms-pagos
server.port=8080

# Base de datos MySQL - completar con datos del servidor
spring.datasource.url=jdbc:mysql://<IP_SERVIDOR>:3306/db_pagos?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=<USUARIO_BD>
spring.datasource.password=<PASSWORD_BD>
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# URL del microservicio de caja
ms.caja.url=http://<IP_SERVIDOR>:<PUERTO_CAJA>
