version: '3.8'

services:

  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: db_pagos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: db_pagos
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pAdmin123"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Microservicio ms-pagos
  ms-pagos:
    build: .
    container_name: ms-pagos
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_pagos?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
