spring.application.name=ms-pagos
server.port=8080

# Base de datos MySQL
# Los datos reales de conexion se configuran en el archivo
# application.yml externo que el administrador ubica en el servidor
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/db_pagos?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Admin123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# URL del microservicio de caja
ms.caja.url=${CAJA_URL:http://localhost:8081}
